// Code generated by Begonia. DO NOT EDIT.
// versions:
// 	Begonia v1.0.2
// begonia base client file

package call

import (
	"github.com/MashiroC/begonia"
	"github.com/MashiroC/begonia/app/option"
)

var BegoniaCli begonia.Client = begonia.NewClientWithAst(option.Addr("xuzhihao.cn:12306"))
