// Code generated by Begonia. DO NOT EDIT.
// versions:
// 	Begonia v1.0.2
// begonia call entity file

package call


	type User struct {
	ID        int `gorm:&#34;primary_key&#34;`
	//CreatedAt time.Time
	//UpdatedAt time.Time
	//DeletedAt *time.Time `sql:&#34;index&#34;`
	Username  string `json:&#34;username&#34; example:&#34;雾好大&#34;`     // 用户登录名
	Password  string `json:&#34;password&#34;  example:&#34;123456&#34;` // 用户登录密码
	Salt      string `json:&#34;salt&#34;`                       //用户密码加密撒盐值
	HeaderImg string `json:&#34;header_img&#34;`                 // 用户头像
}

